const fishList = [
    { emoji: "🐟", name: "Poisson rouge", rarity: "commun", price: 10 },
    { emoji: "🎣", name: "Canne à pêche", rarity: "peu commun", price: 15 },
    { emoji: "🦑", name: "Calmar", rarity: "commun", price: 12 },
    { emoji: "🐡", name: "Poisson-lune", rarity: "peu commun", price: 18 },
    { emoji: "🐠", name: "Poisson tropical", rarity: "commun", price: 10 },
    { emoji: "🦐", name: "Crevette", rarity: "peu commun", price: 20 },
    { emoji: "🦀", name: "Crabe", rarity: "commun", price: 8 },
    { emoji: "🦞", name: "Homard", rarity: "rare", price: 50 },
    { emoji: "🦪", name: "Huître", rarity: "commun", price: 6 },
    { emoji: "🐙", name: "Poulpe", rarity: "rare", price: 40 },
    { emoji: "🐋", name: "Baleine", rarity: "très rare", price: 100 },
    { emoji: "🐬", name: "Dauphin", rarity: "très rare", price: 80 },
    { emoji: "🐚", name: "Coquillage", rarity: "commun", price: 5 },
    { emoji: "🐌", name: "Escargot de mer", rarity: "commun", price: 3 },
    { emoji: "🦈", name: "Requin", rarity: "rare", price: 60 },
    { emoji: "🐠", name: "Poisson-clown", rarity: "peu commun", price: 15 },
    { emoji: "🐡", name: "Poisson-globe", rarity: "rare", price: 45 },
    { emoji: "🦑", name: "Pieuvre", rarity: "rare", price: 55 },
    { emoji: "🐟", name: "Saumon", rarity: "peu commun", price: 20 },
    { emoji: "🐠", name: "Thon", rarity: "peu commun", price: 25 },
  ];
  
  const treasureList = [
    { emoji: "💰", name: "Pièce d'or", rarity: "commun", price: 5 },
    { emoji: "🗝️", name: "Clé", rarity: "peu commun", price: 8 },
    { emoji: "🏴‍☠️", name: "Drapeau pirate", rarity: "rare", price: 60 },
    { emoji: "⚓", name: "Ancre", rarity: "commun", price: 7 },
    { emoji: "🧭", name: "Boussole", rarity: "peu commun", price: 10 },
    { emoji: "🔱", name: "Trident", rarity: "rare", price: 50 },
    { emoji: "📜", name: "Carte au trésor", rarity: "rare", price: 55 },
    { emoji: "🔮", name: "Cristal magique", rarity: "très rare", price: 90 },
    { emoji: "💎", name: "Diamant", rarity: "très rare", price: 120 },
    { emoji: "🌊", name: "Bouteille à la mer", rarity: "rare", price: 40 },
    { emoji: "🔑", name: "Clé dorée", rarity: "très rare", price: 150 },
    { emoji: "🚪", name: "Portail mystérieux", rarity: "très rare", price: 200 },
    { emoji: "🕰️", name: "Montre ancienne", rarity: "très rare", price: 180 },
    { emoji: "📿", name: "Collier de perles", rarity: "rare", price: 65 },
    { emoji: "💰", name: "Trésor enfoui", rarity: "très rare", price: 250 },
    { emoji: "🔱", name: "Couronne royale", rarity: "très rare", price: 300 },
    { emoji: "📜", name: "Ancien parchemin", rarity: "rare", price: 70 },
    { emoji: "🌊", name: "Coquillage doré", rarity: "très rare", price: 180 },
    { emoji: "🍾", name: "Bouteille de champagne", rarity: "rare", price: 75 },
    { emoji: "🏆", name: "Coupe du vainqueur", rarity: "très rare", price: 350 },
  ];
  
  module.exports = { fishList, treasureList };
  