
const fishList = [
  { emoji: "🐟", name: "Poisson rouge", rarity: "commun", price: 10 },
  { emoji: "🎣", name: "Canne à pêche", rarity: "peu commun", price: 15 },
  { emoji: "🦑", name: "Calmar", rarity: "commun", price: 12 },
  { emoji: "🐡", name: "Poisson-lune", rarity: "peu commun", price: 18 },
  { emoji: "🐠", name: "Poisson tropical", rarity: "commun", price: 10 },
  { emoji: "🦐", name: "Crevette", rarity: "peu commun", price: 20 },
  { emoji: "🦀", name: "Crabe", rarity: "commun", price: 8 },
  { emoji: "🦞", name: "Homard", rarity: "rare", price: 50 },
  { emoji: "🦪", name: "Huître", rarity: "commun", price: 6 },
  { emoji: "🐙", name: "Poulpe", rarity: "rare", price: 40 },
  { emoji: "🐋", name: "Baleine", rarity: "très rare", price: 100 },
  { emoji: "🐬", name: "Dauphin", rarity: "très rare", price: 80 },
  { emoji: "🐚", name: "Coquillage", rarity: "commun", price: 5 },
  { emoji: "🐌", name: "Escargot de mer", rarity: "commun", price: 3 },
  { emoji: "🦈", name: "Requin", rarity: "rare", price: 60 },
  { emoji: "🐠", name: "Poisson-clown", rarity: "peu commun", price: 15 },
  { emoji: "🐡", name: "Poisson-globe", rarity: "rare", price: 45 },
  { emoji: "🦑", name: "Pieuvre", rarity: "rare", price: 55 },
  { emoji: "🐟", name: "Saumon", rarity: "peu commun", price: 20 },
  { emoji: "🐠", name: "Thon", rarity: "peu commun", price: 25 },
  { emoji: "🐟", name: "Anguille", rarity: "peu commun", price: 30 },
  { emoji: "🐠", name: "Poisson-perroquet", rarity: "commun", price: 12 },
  { emoji: "🦈", name: "Requin-marteau", rarity: "rare", price: 70 },
  { emoji: "🐟", name: "Maquereau", rarity: "commun", price: 8 },
  { emoji: "🐠", name: "Poisson-ange", rarity: "rare", price: 50 },
  { emoji: "🐡", name: "Fugu", rarity: "très rare", price: 100 },
  { emoji: "🦑", name: "Kraken", rarity: "très rare", price: 200 },
  { emoji: "🐬", name: "Narval", rarity: "très rare", price: 150 },
  { emoji: "🐠", name: "Sole", rarity: "commun", price: 10 },
  { emoji: "🦐", name: "Langoustine", rarity: "rare", price: 60 },
  { emoji: "🦞", name: "Écrevisse", rarity: "peu commun", price: 25 },
  { emoji: "🐙", name: "Seiche", rarity: "commun", price: 10 },
  { emoji: "🐟", name: "Bar", rarity: "commun", price: 15 },
  { emoji: "🐠", name: "Gobie", rarity: "commun", price: 5 },
  { emoji: "🐟", name: "Truite", rarity: "commun", price: 10 },
  { emoji: "🐠", name: "Arapaima", rarity: "rare", price: 70 },
  { emoji: "🦑", name: "Nautile", rarity: "rare", price: 55 },
  { emoji: "🐋", name: "Orque", rarity: "très rare", price: 180 },
  { emoji: "🦀", name: "Crabe royal", rarity: "rare", price: 80 },
  { emoji: "🐠", name: "Carangue", rarity: "commun", price: 15 },
  { emoji: "🐟", name: "Dorade", rarity: "commun", price: 12 },
  { emoji: "🦈", name: "Mégalodon", rarity: "très rare", price: 300 },
  { emoji: "🐠", name: "Turbot", rarity: "commun", price: 20 },
  { emoji: "🐟", name: "Flétan", rarity: "peu commun", price: 35 },
  { emoji: "🐠", name: "Poisson-licorne", rarity: "rare", price: 90 },
  { emoji: "🐟", name: "Morue", rarity: "commun", price: 15 },
  { emoji: "🐠", name: "Chinchard", rarity: "commun", price: 7 },
  { emoji: "🐟", name: "Hippocampe", rarity: "peu commun", price: 30 },
];

const treasureList = [
  { emoji: "💰", name: "Pièce d'or", rarity: "commun", price: 5 },
  { emoji: "🗝️", name: "Clé", rarity: "peu commun", price: 8 },
  { emoji: "🏴‍☠️", name: "Drapeau pirate", rarity: "rare", price: 60 },
  { emoji: "⚓", name: "Ancre", rarity: "commun", price: 7 },
  { emoji: "🧭", name: "Boussole", rarity: "peu commun", price: 10 },
  { emoji: "🔱", name: "Trident", rarity: "rare", price: 50 },
  { emoji: "📜", name: "Carte au trésor", rarity: "rare", price: 55 },
  { emoji: "🔮", name: "Cristal magique", rarity: "très rare", price: 90 },
  { emoji: "💎", name: "Diamant", rarity: "très rare", price: 120 },
  { emoji: "🌊", name: "Bouteille à la mer", rarity: "rare", price: 40 },
  { emoji: "🔑", name: "Clé dorée", rarity: "très rare", price: 150 },
  { emoji: "🚪", name: "Portail mystérieux", rarity: "très rare", price: 200 },
  { emoji: "🕰️", name: "Montre ancienne", rarity: "très rare", price: 180 },
  { emoji: "📿", name: "Collier de perles", rarity: "rare", price: 65 },
  { emoji: "💰", name: "Trésor enfoui", rarity: "très rare", price: 250 },
  { emoji: "🔱", name: "Couronne royale", rarity: "très rare", price: 300 },
  { emoji: "📜", name: "Ancien parchemin", rarity: "rare", price: 70 },
  { emoji: "🌊", name: "Coquillage doré", rarity: "très rare", price: 180 },
  { emoji: "🍾", name: "Bouteille de champagne", rarity: "rare", price: 75 },
  { emoji: "🏆", name: "Coupe du vainqueur", rarity: "très rare", price: 350 },
  { emoji: "🗺️", name: "Carte ancienne", rarity: "peu commun", price: 20 },
  { emoji: "🔨", name: "Marteau de Thor", rarity: "très rare", price: 400 },
  { emoji: "⚱️", name: "Vase antique", rarity: "rare", price: 100 },
  { emoji: "💍", name: "Bague précieuse", rarity: "très rare", price: 500 },
  { emoji: "🔔", name: "Cloche dorée", rarity: "rare", price: 120 },
  { emoji: "🧳", name: "Vieille valise", rarity: "peu commun", price: 30 },
  { emoji: "📚", name: "Livre ancien", rarity: "rare", price: 80 },
  { emoji: "🗝️", name: "Clé en argent", rarity: "rare", price: 90 },
  { emoji: "🔮", name: "Boule de cristal", rarity: "très rare", price: 250 },
  { emoji: "👑", name: "Diadème", rarity: "très rare", price: 300 },
  { emoji: "⚔️", name: "Épée légendaire", rarity: "très rare", price: 600 },
  { emoji: "🛡️", name: "Bouclier d'argent", rarity: "rare", price: 200 },
  { emoji: "🏺", name: "Amphore grecque", rarity: "rare", price: 130 },
  { emoji: "🏺", name: "Urne romaine", rarity: "rare", price: 110 },
  { emoji: "🗿", name: "Statue ancienne", rarity: "très rare", price: 700 },
  { emoji: "🧸", name: "Vieux ours en peluche", rarity: "peu commun", price: 20 },
  { emoji: "🖋️", name: "Plume ancienne", rarity: "peu commun", price: 50 },
  { emoji: "🎻", name: "Violon rare", rarity: "très rare", price: 650 },
  { emoji: "🏺", name: "Vase en or", rarity: "très rare", price: 500 },
  { emoji: "📜", name: "Manuscrit rare", rarity: "très rare", price: 450 },
  { emoji: "💼", name: "Mallette secrète", rarity: "très rare", price: 300 },
  { emoji: "🎠", name: "Miniature de carrousel", rarity: "rare", price: 140 },
  { emoji: "🏺", name: "Jarre ancienne", rarity: "rare", price: 160 },
  { emoji: "🎩", name: "Chapeau de magicien", rarity: "rare", price: 220 },
];

const fruitVegList = [
  // Fruits
  { emoji: "🍎", name: "Pomme", rarity: "commun", price: 20 },
  { emoji: "🍌", name: "Banane", rarity: "commun", price: 10 },
  { emoji: "🍇", name: "Raisin", rarity: "peu commun", price: 30 },
  { emoji: "🍉", name: "Pastèque", rarity: "commun", price: 40 },
  { emoji: "🍓", name: "Fraise", rarity: "commun", price: 20 },
  { emoji: "🍒", name: "Cerise", rarity: "peu commun", price: 50 },
  { emoji: "🍍", name: "Ananas", rarity: "commun", price: 30 },
  { emoji: "🍑", name: "Pêche", rarity: "commun", price: 20 },
  { emoji: "🍐", name: "Poire", rarity: "commun", price: 20 },
  { emoji: "🍊", name: "Orange", rarity: "commun", price: 10 },
  { emoji: "🍋", name: "Citron", rarity: "commun", price: 10 },
  { emoji: "🍈", name: "Melon", rarity: "peu commun", price: 30 },
  { emoji: "🥭", name: "Mangue", rarity: "peu commun", price: 40 },
  { emoji: "🥝", name: "Kiwi", rarity: "peu commun", price: 30 },
  { emoji: "🥥", name: "Noix de coco", rarity: "rare", price: 60 },
  { emoji: "🍏", name: "Pomme verte", rarity: "commun", price: 20 },
  { emoji: "🍅", name: "Tomate", rarity: "commun", price: 10 },
  { emoji: "🍋", name: "Citron vert", rarity: "commun", price: 10 },
  { emoji: "🍇", name: "Raisin rouge", rarity: "commun", price: 25 },
  { emoji: "🥭", name: "Papaye", rarity: "peu commun", price: 30 },
  { emoji: "🍋", name: "Citron Meyer", rarity: "peu commun", price: 25 },
  { emoji: "🍈", name: "Melon cantaloup", rarity: "peu commun", price: 30 },
  { emoji: "🍍", name: "Ananas Victoria", rarity: "rare", price: 60 },
  { emoji: "🍓", name: "Fraise blanche", rarity: "rare", price: 50 },
  { emoji: "🥥", name: "Noix de coco jeune", rarity: "rare", price: 70 },

  // Légumes
  { emoji: "🥦", name: "Brocoli", rarity: "commun", price: 20 },
  { emoji: "🥬", name: "Laitue", rarity: "commun", price: 10 },
  { emoji: "🥒", name: "Concombre", rarity: "commun", price: 20 },
  { emoji: "🥕", name: "Carotte", rarity: "commun", price: 10 },
  { emoji: "🥔", name: "Pomme de terre", rarity: "commun", price: 10 },
  { emoji: "🍆", name: "Aubergine", rarity: "commun", price: 20 },
  { emoji: "🌽", name: "Maïs", rarity: "commun", price: 20 },
  { emoji: "🍄", name: "Champignon", rarity: "peu commun", price: 30 },
  { emoji: "🌶️", name: "Piment", rarity: "peu commun", price: 30 },
  { emoji: "🥑", name: "Avocat", rarity: "peu commun", price: 40 },
  { emoji: "🥦", name: "Chou-fleur", rarity: "commun", price: 20 },
  { emoji: "🍠", name: "Patate douce", rarity: "commun", price: 15 },
  { emoji: "🥔", name: "Igname", rarity: "peu commun", price: 25 },
  { emoji: "🍆", name: "Courgette", rarity: "commun", price: 20 },
  { emoji: "🍠", name: "Rutabaga", rarity: "peu commun", price: 30 },
  { emoji: "🍄", name: "Truffe", rarity: "rare", price: 100 },
  { emoji: "🌰", name: "Châtaigne", rarity: "peu commun", price: 25 },
  { emoji: "🌿", name: "Basilic", rarity: "peu commun", price: 15 },
  { emoji: "🌾", name: "Blé", rarity: "commun", price: 10 },
  { emoji: "🥒", name: "Cornichon", rarity: "commun", price: 10 },
  { emoji: "🌽", name: "Pop-corn", rarity: "peu commun", price: 25 },
  { emoji: "🥕", name: "Carotte violette", rarity: "peu commun", price: 25 },
  { emoji: "🍠", name: "Navet", rarity: "commun", price: 15 },
  { emoji: "🍆", name: "Chou", rarity: "commun", price: 20 },
  { emoji: "🥬", name: "Épinard", rarity: "commun", price: 20 }
];


const minecraft = [
  { emoji: "<:grass_block_side:1261703772636319844>", name: "Bloc d'herbe", rarity: "commun", price: 10 },
  { emoji: "<:dirt:1261703521229733888>", name: "Terre", rarity: "commun", price: 5 },
  { emoji: "<:stone:1262795425497481269>", name: "Pierre", rarity: "commun", price: 10 },

  { emoji: "<:deepslate:1261703465080590388>", name: "Pierre des abîmes", rarity: "commun", price: 6 },

  { emoji: "<:coal_ore:1262795649577914471>", name: "Minerai de charbon", rarity: "commun", price: 15 },
  { emoji: "<:iron_ore:1261703920581869608>", name: "Minerai de fer", rarity: "peu commun", price: 25 },
  { emoji: "<:lapis_ore:1261703995861499976>", name: "Minerai de lapis-lazuli", rarity: "peu commun", price: 30 },
  { emoji: "<:redstone_ore:1261718294381990020>", name: "Minerai de redstone", rarity: "peu commun", price: 30 },
  { emoji: "<:gold_ore:1261703784376172675>", name: "Minerai d'or", rarity: "rare", price: 50 },
  { emoji: "<:emerald_ore:1261703581774512149>", name: "Minerai d'émeraude", rarity: "rare", price: 70 },
  { emoji: "<:diamond_ore:1261703523649847378>", name: "Minerai de diamant", rarity: "rare", price: 100 },

  { emoji: "<:oak_log:1261704217807028294>", name: "Bûche de chêne", rarity: "commun", price: 20 },
  { emoji: "<:acacia_log:1261678705386721362>", name: "Bûche d'acacia", rarity: "commun", price: 20 },
  { emoji: "<:cherry_log:1261701455794933860>", name: "Bûche de cerisier", rarity: "commun", price: 20 },
  { emoji: "<:birch_log:1261700897466220574>", name: "Bûche de bouleau", rarity: "commun", price: 20 },
  { emoji: "<:dark_oak_log:1261703414849732700>", name: "Bûche de chêne noir", rarity: "commun", price: 20 },
  { emoji: "<:jungle_log:1261703990941450310>", name: "Bûche d'acajou", rarity: "commun", price: 20 },
  { emoji: "<:mangrove_log:1261704083195170858>", name: "Bûche de palétuvier", rarity: "commun", price: 20 },
  { emoji: "<:spruce_log:1262827729385164850>", name: "Bûche de sapin", rarity: "commun", price: 20 },
  { emoji: "<:bamboo_block:1261678923776000101>", name: "Bloc de bambou", rarity: "commun", price: 15 },

  { emoji: "<:crafting_table_front:1262828333024940112>", name: "Etabli", rarity: "peu commun", price: 40 },
  { emoji: "<:furnace_front:1261703700666384405>", name: "Four", rarity: "peu commun", price: 35 },

  { emoji: "<:dispenser_front:1261703548530589840>", name: "Distributeur", rarity: "rare", price: 80 },
  { emoji: "<:dropper_front:1261703567778254982>", name: "Droppeur", rarity: "rare", price: 80 },
  { emoji: "<:enchanting_table_side:1261703591757090817>", name: "Table d'enchantement", rarity: "très rare", price: 200 },
  { emoji: "<:end_portal_frame_side:1261703611239370834>", name: "Morceau de portail de l'end", rarity: "très rare", price: 250 },
  { emoji: "<:loom_front:1261704039700238448>", name: "Loom", rarity: "rare", price: 30 },

  { emoji: "<:oak_planks:1261704216251207710>", name: "Planche de chêne", rarity: "peu commun", price: 30 },
  { emoji: "<:acacia_planks:1261678707982995467>", name: "Planche d'acacia", rarity: "peu commun", price: 30 },
  { emoji: "<:cherry_planks:1261701470626250814>", name: "Planche de cerisier", rarity: "peu commun", price: 30 },
  { emoji: "<:birch_planks:1261679497024110632>", name: "Planche de bouleau", rarity: "peu commun", price: 30 },
  { emoji: "<:dark_oak_planks:1261703422776967250>", name: "Planche de chêne noir", rarity: "peu commun", price: 30 },
  { emoji: "<:jungle_planks:1261703992212328618>", name: "Planche d'acajou", rarity: "peu commun", price: 30 },
  { emoji: "<:mangrove_planks:1261704084411519057>", name: "Planche de palétuvier", rarity: "peu commun", price: 30 },
  { emoji: "<:spruce_planks:1262829412382933012>", name: "Planche de sapin", rarity: "peu commun", price: 30 },
  { emoji: "<:bamboo_planks:1261679071608311969>", name: "Planche de bambou", rarity: "commun", price: 15 },
];



module.exports = { fishList, treasureList, fruitVegList, minecraft };
